const Contract = require('../models/contractModel')
const Property = require('../models/propertyModel')
const User = require('../models/usersModel')
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib')

// Generate a simple signed PDF for a contract
const generateContractPdf = async (req, res) => {
  try {
    const id = req.params.id
    const contract = await Contract.findById(id).populate('property owner renter')
    if (!contract) return res.status(404).json({ success: false, message: 'Contract not found' })

    // Build a plain-text representation of the contract for the PDF
    const lines = []
    lines.push('Residential Rental Agreement')
    lines.push('')
    lines.push(`Contract ID: ${contract._id}`)
    lines.push(`Property: ${contract.property?.address || contract.property || ''}`)
    lines.push(`Owner: ${contract.owner?.name || contract.owner || ''}`)
    lines.push(`Renter: ${contract.renter?.name || contract.renter || ''}`)
    lines.push('')
    lines.push(`Effective: ${contract.createdAt ? contract.createdAt.toISOString() : new Date().toISOString()}`)
    lines.push('')
    lines.push('Term:')
    lines.push(`  Start: ${contract.startDate ? contract.startDate.toISOString().slice(0,10) : ''}`)
    lines.push(`  End:   ${contract.endDate ? contract.endDate.toISOString().slice(0,10) : ''}`)
    lines.push('')
    lines.push('Payment:')
    lines.push(`  Rent: ${contract.rentAmount || ''} ${contract.currency || ''}`)
    lines.push(`  Security deposit: ${contract.securityDeposit || ''}`)
    lines.push('')
    lines.push('Signatures:')
    if (contract.ownerAccepted && contract.ownerAccepted.accepted) {
      lines.push(`  Owner: ${contract.ownerAccepted.signature?.name || contract.owner?.name || ''}`)
      lines.push(`    At: ${contract.ownerAccepted.at ? contract.ownerAccepted.at.toISOString() : ''}`)
    } else {
      lines.push('  Owner: (not signed)')
    }

    if (contract.renterAccepted && contract.renterAccepted.accepted) {
      lines.push(`  Renter: ${contract.renterAccepted.signature?.name || contract.renter?.name || ''}`)
      lines.push(`    At: ${contract.renterAccepted.at ? contract.renterAccepted.at.toISOString() : ''}`)
    } else {
      lines.push('  Renter: (not signed)')
    }

    lines.push('')
    lines.push('This document was generated by the Rentify web application.')

    // Create PDF
    const pdfDoc = await PDFDocument.create()
    let page = pdfDoc.addPage()
    const { width, height } = page.getSize()
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
    const fontSize = 11
    const margin = 50
    let y = height - margin

    page.drawText('Residential Rental Agreement', { x: margin, y: y, size: 14, font, color: rgb(0,0,0) })
    y -= 22

    for (const line of lines) {
      if (y < margin + 30) {
        // add new page
        page = pdfDoc.addPage()
      }
      page.drawText(line, { x: margin, y: y, size: fontSize, font, color: rgb(0,0,0) })
      y -= fontSize + 6
    }

    const pdfBytes = await pdfDoc.save()

    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', `attachment; filename=contract-${id}.pdf`)
    return res.send(Buffer.from(pdfBytes))
  } catch (err) {
    console.error('generateContractPdf', err)
    return res.status(500).json({ success: false, message: err.message })
  }
}

module.exports = { generateContractPdf };
